# Generated by Django 2.2.24 on 2021-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='knowledge',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
