# Generated by Django 2.2.24 on 2021-10-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='knowledge',
            field=models.IntegerField(),
        ),
    ]
